export enum WeatherType {
    ExtraSunny = 'EXTRASUNNY',
    Clear = 'CLEAR',
    Clouds = 'CLOUDS',
    Smog = 'SMOG',
    Foggy = 'FOGGY',
    Overcast = 'OVERCAST',
    Rain = 'RAIN',
    Thunder = 'THUNDER',
    Clearing = 'CLEARING',
    Neutral = 'NEUTRAL',
    Snow = 'SNOW',
    Blizzard = 'BLIZZARD',
    SnowLight = 'SNOWLIGHT',
    Xmas = 'XMAS',
    Halloween = 'HALLOWEEN',
    RainHalloween = 'RAIN_HALLOWEEN',
    SnowHalloween = 'SNOW_HALLOWEEN',
}
